
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CONST FinP InP PROC VAR coma idS : PROC id InP L FinPL : V\n       | C\n       | V coma L\n       | C coma LV : VAR idC : CONST id'
    
_lr_action_items = {'PROC':([0,],[2,]),'$end':([1,10,],[0,-1,]),'id':([2,8,9,],[3,13,14,]),'InP':([3,],[4,]),'VAR':([4,11,12,],[8,8,8,]),'CONST':([4,11,12,],[9,9,9,]),'FinP':([5,6,7,13,14,15,16,],[10,-2,-3,-6,-7,-4,-5,]),'coma':([6,7,13,14,],[11,12,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'L':([4,11,12,],[5,15,16,]),'V':([4,11,12,],[6,6,6,]),'C':([4,11,12,],[7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> PROC id InP L FinP','S',5,'p_S','AnSintac.py',19),
  ('L -> V','L',1,'p_L','AnSintac.py',23),
  ('L -> C','L',1,'p_L','AnSintac.py',24),
  ('L -> V coma L','L',3,'p_L','AnSintac.py',25),
  ('L -> C coma L','L',3,'p_L','AnSintac.py',26),
  ('V -> VAR id','V',2,'p_V','AnSintac.py',30),
  ('C -> CONST id','C',2,'p_C','AnSintac.py',34),
]
