
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HR finB finBODY finHEAD finHTML finP finTITLE inicioB inicioBODY inicioHEAD inicioHTML inicioP inicioTITLE textoS : inicioHTML html finHTMLhtml : inicioHEAD head finHEAD inicioBODY body finBODYhead : inicioTITLE textoPagina finTITLEbody : parrafo\n          | parrafo : inicioP content finP bodycontent : textoPagina content\n             | HR content\n             | inicioB content finB content\n             | textoPagina : texto textoPagina\n                 | '
    
_lr_action_items = {'inicioHTML':([0,],[2,]),'$end':([1,5,],[0,-1,]),'inicioHEAD':([2,],[4,]),'finHTML':([3,17,],[5,-2,]),'inicioTITLE':([4,],[7,]),'finHEAD':([6,12,],[8,-3,]),'texto':([7,10,13,16,19,20,21,27,],[10,10,-11,10,10,10,10,10,]),'finTITLE':([7,9,10,13,],[-12,12,-12,-11,]),'inicioBODY':([8,],[11,]),'HR':([10,13,16,19,20,21,27,],[-12,-11,20,20,20,20,20,]),'inicioB':([10,13,16,19,20,21,27,],[-12,-11,21,21,21,21,21,]),'finP':([10,13,16,18,19,20,23,24,27,28,],[-12,-11,-10,22,-10,-10,-7,-8,-10,-9,]),'finB':([10,13,19,20,21,23,24,25,27,28,],[-12,-11,-10,-10,-10,-7,-8,27,-10,-9,]),'finBODY':([11,14,15,22,26,],[-5,17,-4,-5,-6,]),'inicioP':([11,22,],[16,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'html':([2,],[3,]),'head':([4,],[6,]),'textoPagina':([7,10,16,19,20,21,27,],[9,13,19,19,19,19,19,]),'body':([11,22,],[14,26,]),'parrafo':([11,22,],[15,15,]),'content':([16,19,20,21,27,],[18,23,24,25,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> inicioHTML html finHTML','S',3,'p_S','AnSintac.py',20),
  ('html -> inicioHEAD head finHEAD inicioBODY body finBODY','html',6,'p_html','AnSintac.py',24),
  ('head -> inicioTITLE textoPagina finTITLE','head',3,'p_head','AnSintac.py',28),
  ('body -> parrafo','body',1,'p_body','AnSintac.py',32),
  ('body -> <empty>','body',0,'p_body','AnSintac.py',33),
  ('parrafo -> inicioP content finP body','parrafo',4,'p_parrafo','AnSintac.py',37),
  ('content -> textoPagina content','content',2,'p_content','AnSintac.py',41),
  ('content -> HR content','content',2,'p_content','AnSintac.py',42),
  ('content -> inicioB content finB content','content',4,'p_content','AnSintac.py',43),
  ('content -> <empty>','content',0,'p_content','AnSintac.py',44),
  ('textoPagina -> texto textoPagina','textoPagina',2,'p_textoPagina','AnSintac.py',48),
  ('textoPagina -> <empty>','textoPagina',0,'p_textoPagina','AnSintac.py',49),
]
