
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FinP InP num sum timesE : T EprimaEprima : sum T Eprima\n            | T : F TprimaTprima : times F Tprima\n            | F : num\n       | InP E FinP'
    
_lr_action_items = {'num':([0,5,7,9,],[4,4,4,4,]),'InP':([0,5,7,9,],[5,5,5,5,]),'$end':([1,2,3,4,6,8,11,12,13,14,15,],[0,-3,-6,-7,-1,-4,-3,-6,-8,-2,-5,]),'sum':([2,3,4,8,11,12,13,15,],[7,-6,-7,-4,7,-6,-8,-5,]),'FinP':([2,3,4,6,8,10,11,12,13,14,15,],[-3,-6,-7,-1,-4,13,-3,-6,-8,-2,-5,]),'times':([3,4,12,13,],[9,-7,9,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,5,],[1,10,]),'T':([0,5,7,],[2,2,11,]),'F':([0,5,7,9,],[3,3,3,12,]),'Eprima':([2,11,],[6,14,]),'Tprima':([3,12,],[8,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> T Eprima','E',2,'p_E','AnSintac.py',24),
  ('Eprima -> sum T Eprima','Eprima',3,'p_Eprima','AnSintac.py',28),
  ('Eprima -> <empty>','Eprima',0,'p_Eprima','AnSintac.py',29),
  ('T -> F Tprima','T',2,'p_T','AnSintac.py',33),
  ('Tprima -> times F Tprima','Tprima',3,'p_Tprima','AnSintac.py',37),
  ('Tprima -> <empty>','Tprima',0,'p_Tprima','AnSintac.py',38),
  ('F -> num','F',1,'p_F','AnSintac.py',42),
  ('F -> InP E FinP','F',3,'p_F','AnSintac.py',43),
]
